export type ExternalHealthSource = 'oura' | 'apple_health';

export type ExternalHealthDailySnapshot = {
  userId: string;
  source: ExternalHealthSource;
  localDate: string;
  timezone: string;
  sleepScore: number | null;
  readinessScore: number | null;
  activityScore: number | null;
  stressHighSeconds: number | null;
  recoveryHighSeconds: number | null;
  steps: number | null;
  activeCalories: number | null;
  totalCalories: number | null;
  averageSpo2: number | null;
  breathingDisturbanceIndex: number | null;
  vo2Max: number | null;
  restingHeartRate: number | null;
  hrvBalance: string | null;
  resilienceLevel: string | null;
  cardiovascularAge: number | null;
  sleepAvgHrv: number | null;
  sleepEfficiency: number | null;
  sleepLatencySeconds: number | null;
  deepSleepMinutes: number | null;
  remSleepMinutes: number | null;
  respiratoryRate: number | null;
  temperatureDeviation: number | null;
  temperatureTrendDeviation: number | null;
  nonWearMinutes: number | null;
  deepSleepFirstThirdMinutes: number | null;
  minutesToFirstDeepSleep: number | null;
  hrvRecoveryDelta: number | null;
  workoutCount: number;
  rawPayload: Record<string, unknown>;
};
